import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { FaArrowRight, FaArrowUp, FaPen } from "react-icons/fa";

import Header from "../components/header";
import HeroSection from "../components/hero";
import ServicesGrid from "../components/services";
import Features from "../components/features";
import Footer from "../components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <HeroSection
          title="School Journal"
          subtitle="Цифровой журнал учебных заведений"
        >
          <p>
            Учет учащихся в электронном виде на одной платформе <br /> между
            разными устройствами
          </p>
        </HeroSection>

        <section>
          <h3> Навигация и помощь </h3>
          <h2 className="text-center"> Что вы бы хотели сделать? </h2>

          <p className="text-center">
            Выберите операцию которую вы бы хотели сделать прямо сейчас и
            получите к ней быстрый доступ
          </p>

          <ServicesGrid />
        </section>

        <section>
          <h3> О сервисе </h3>
          <h2 className="text-center"> Обучайся просто прямо сейчас </h2>

          <p className="text-center">
            Онлайн сервис для учащихся и учителей собравший в одном месте учет
            успеваемости и связь между всеми
          </p>

          <p className="text-center">
            Платформа разработана специально для удобного и централизированного
            использования всеми его участниками, среди возможностей имеется:
          </p>

          <Features />
        </section>

        <section>
          <h3> Новости </h3>
          <h2 className="text-center"> Блоги учителей </h2>

          <p className="text-center">
            Читайте блоги сделанные специалистами в своей сфере, получайте
            дополнительные знания и делитесь мнениями
          </p>

          <div className="news">
            <div>
              <div>
                <div>
                  <Image
                    src="/img/avatars/man1.png"
                    alt="Павлов Георгий Тарасович"
                    width={48}
                    height={48}
                  />

                  <h3>Павлов Георгий Тарасович</h3>
                </div>

                <FaPen />
              </div>

              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Obcaecati odit nemo placeat, consectetur necessitatibus nisi
                quasi earum ipsam nesciunt sed assumenda natus laboriosam sint
                nam culpa perspiciatis vitae sit minus!
              </p>

              <div>
                <Link href="/blog">
                  <a>
                    Перейти <FaArrowRight />
                  </a>
                </Link>

                <p>
                  <span> IT Карьера </span> &bull; 18 декабря 2022
                </p>
              </div>
            </div>

            <div>
              <div>
                <div>
                  <Image
                    src="/img/avatars/woman1.png"
                    alt="Федосеева Варвара Руслановна"
                    width={48}
                    height={48}
                  />

                  <h3>Федосеева Варвара Руслановна</h3>
                </div>

                <FaPen />
              </div>

              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Obcaecati odit nemo placeat, consectetur necessitatibus nisi
                quasi earum ipsam nesciunt sed assumenda natus laboriosam sint
                nam culpa perspiciatis vitae sit minus!
              </p>

              <div>
                <Link href="/blog">
                  <a>
                    Перейти <FaArrowRight />
                  </a>
                </Link>

                <p>
                  <span> Литература </span> &bull; 2 февраля 2022
                </p>
              </div>
            </div>
          </div>
        </section>

        <section>
          <h3> Вернутся </h3>
          <h2 className="text-center"> Начни использовать уже сейчас </h2>

          <p className="text-center">
            Понравилась платформа? вернись с помощью кнопки ниже что-бы начать
          </p>

          <Link href="#hero">
            <a className="button">
              Вернутся <FaArrowUp />
            </a>
          </Link>
        </section>
      </main>

      <Footer />
    </>
  );
}
